//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class students_mark
    {
        public int student_id { get; set; }
        public int test_id { get; set; }
        public int mark { get; set; }
    
        public virtual student student { get; set; }
        public virtual test test { get; set; }
    }
}
