//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_answer
    {
        public int student_answer_id { get; set; }
        public int student_id { get; set; }
        public int question_test_id { get; set; }
        public int ans_id { get; set; }
    
        public virtual answer answer { get; set; }
        public virtual student student { get; set; }
    }
}
